TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1
  min_vel_x: 0.1

  max_vel_theta:  0.261799388 
  min_vel_theta: -0.261799388 
  min_in_place_vel_theta: 0.261799388 

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.13 

# Goal Tolerance Parameters
  xy_goal_tolerance: 1
  yaw_goal_tolerance: 6.28318531

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
