TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1.0
  min_vel_x: 0.2

  max_vel_theta: 0.26
  min_vel_theta: -0.26
  min_in_place_vel_theta: 0.26

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.15

# Goal Tolerance Parameters
  xy_goal_tolerance: 1
  yaw_goal_tolerance: 6.2

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
