DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1.0
  min_vel_x: 0.2

  # max_vel_y: 0.0
  # min_vel_y: 0.0
  meter_scoring : true

# The velocity when robot is moving in a straight line
  max_vel_trans:  1.0
  min_vel_trans:  0.2

  max_vel_theta: 0.26
  min_vel_theta: -0.26 

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.15

# Goal Tolerance Parameters
  xy_goal_tolerance: 1.0
  yaw_goal_tolerance: 6.2
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 20
  vy_samples: 0.0
  vth_samples: 40
  controller_frequency: 2.0

# Trajectory Scoring Parameters
  path_distance_bias: 20.0    # the more the value is the more the local path follow the global path [0:]
  goal_distance_bias: 30.0    # the 
  occdist_scale: 0.04
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
